### ISSUE TITLE
Selector.select() returned prematurely 512 times in a row; rebuilding selector

### ISSUE THREAD

**Issue by frkline** [impossibl/pgjdbc-ng#191] opened 2015-07-23 05:18 UTC
Saw this error message pop up once in our server-side logs over the last week:

```
2015-07-22 09:42:04,273 WARN PG-JDBC EventLoop (1) NioEventLoop.warn - Selector.select() returned prematurely 512 times in a row; rebuilding selector.
```

Using 0.5 with https://github.com/brettwooldridge/HikariCP

**Comment by kdubb** [comment] 2015-07-23 05:21
What version are you using?

**Comment by kdubb** [comment] 2015-07-23 05:23
It's listed as "not a bug" in netty project. Are you using the versions of Linux/Java referenced here https://github.com/netty/netty/issues/2616 ?

**Comment by frkline** [comment] 2015-07-23 05:37
We're using 0.5 via Maven Central.

Kernel:

```
~$ uname -r
3.19.0
```

Java:

```
~$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

**Comment by PatrickHuetter** [comment] 2015-12-10 15:18
Same problem here with linux kernel 4.2 and 3.16 and java 7.

**Comment by kdubb** [comment] 2016-07-10 04:17
Closing as this appears to be Netty & specific Linux kernel versions related

**Closed as completed by kdubb** 2016-07-10 04:17 UTC
