### ISSUE TITLE
CallableStatement: calling "schema.function()" throws java.sql.SQLException: Invalid escape syntax (0)

### ISSUE THREAD

**Issue by vanecanhete** [impossibl/pgjdbc-ng#92] opened 2014-08-14 20:03 UTC
I have this function in postgres. 

``` plpgsql
CREATE OR REPLACE FUNCTION pruebas.prueba()
  RETURNS void AS
$BODY$
begin
    update apns set descripcion = 'MODIFICADO' where apnid = '111';
end;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION pruebas.prueba()
  OWNER TO postgres;
```

I want to call it from Java like this: 

``` java
    public static void main(String[] args) throws Exception {
        System.out.println(" ************** Prueba Package Function ************* ");
        Connection conn = Main.openDB();
        CallableStatement call = conn.prepareCall("{call pruebas.prueba()}");
        call.execute();
        call.close();
        Main.closeDB(conn);
    }
```

I'm getting this exception: 
 *************\* Prueba Package Function ************\* 
Exception in thread "main" java.sql.SQLException: Invalid escape syntax (0)
    at com.impossibl.postgres.jdbc.SQLTextEscapes.checkSize(SQLTextEscapes.java:300)
    at com.impossibl.postgres.jdbc.SQLTextEscapes.checkSize(SQLTextEscapes.java:289)
    at com.impossibl.postgres.jdbc.SQLTextEscapes.processCallEscape(SQLTextEscapes.java:250)
    at com.impossibl.postgres.jdbc.SQLTextEscapes.processEscape(SQLTextEscapes.java:111)
    at com.impossibl.postgres.jdbc.SQLTextEscapes.access$000(SQLTextEscapes.java:63)
    at com.impossibl.postgres.jdbc.SQLTextEscapes$1.process(SQLTextEscapes.java:76)
    at com.impossibl.postgres.jdbc.SQLTextTree$CompositeNode.process(SQLTextTree.java:192)
    at com.impossibl.postgres.jdbc.SQLTextTree$CompositeNode.process(SQLTextTree.java:178)
    at com.impossibl.postgres.jdbc.SQLTextTree$CompositeNode.process(SQLTextTree.java:178)
    at com.impossibl.postgres.jdbc.SQLText.process(SQLText.java:92)
    at com.impossibl.postgres.jdbc.SQLTextEscapes.processEscapes(SQLTextEscapes.java:67)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.prepareCall(PGConnectionImpl.java:1048)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.prepareCall(PGConnectionImpl.java:1028)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.prepareCall(PGConnectionImpl.java:1019)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.prepareCall(PGConnectionImpl.java:1014)
    at py.com.personal.PGDriver.Main.main(Main.java:130)

It works when I put the function in public schema, but I need it in another schema. 
How can I call the function?

**Comment by valgog** [comment] 2014-08-15 09:08
I suppose, that you can try to set the `search_path to pruebas, public;` in the connection before calling that function without specified the schema. I have not looked into the code though to understand if it is a problem with parsing of the call JDBC syntax or a more general problem.

Alternatively try to call using `select * from pruebas.prueba();`. This will also show if it is the problem with the parsing of syntax as mentioned before.

**Comment by valgog** [comment] 2014-08-15 09:10
Oh, just noticed that exception text :) Most probably this is a parsing issue, so just try the select syntax first.

**Comment by gsmet** [comment] 2014-08-15 09:24
Hi,

The problem is in SQLTextEscapes.processCallEscape(EscapeNode escape).

The code is the following:
  private static Node processCallEscape(EscapeNode escape) throws
SQLException {

```
escape.removeAll(WhitespacePiece.class, false);

checkSize(escape, 2, 3);

return groupedSequence("SELECT", space(), grammar("*"), "FROM",
```

getNode(escape, 1, UnquotedIdentifierPiece.class), space(), getNode(escape,
2, ParenGroupNode.class));
  }

The checkSize call checks that there at least 2 nodes and at most 3. But in
the case of a call with a schema qualified path, you have 5 nodes:
[call, pruebas, ., prueba, ()]

I think, the checkSize call should be changed to checkSize(escape, 2, 3, 5);

Kevin, if you agree with this fix, I can work on a PR with the fix and a
test.

## 

Guillaume

**Comment by gsmet** [comment] 2014-08-15 09:25
Note: we also have to fix processCallEscape to take this case into account
and generate a schema qualified path in the generated query.

**Comment by kdubb** [comment] 2014-08-18 02:55
Do we know if this syntax is part of JDBC?

**Comment by gsmet** [comment] 2014-08-18 06:58
Hard to say. The javadoc says <procedure name>. I haven't found any other information.

I think we should support schema qualified name one way or the other.

**Comment by valgog** [comment] 2014-08-18 09:02
The questions is, why you want to use this strange syntax other then for compatibility with other databases and their JDBC drivers, that do not have a concept of postgres namespaces?

**Comment by kdubb** [comment] 2014-08-18 13:50
@valgog You have expressed my point exactly.  JDBC escape is for compatibility.  PostgreSQL namespaces are inherently incompatible.

@vanecan If you wish to preserve compatibility and use namespaces maybe @valgog 's suggestion of using the search_path is the correct one.  It means you can use namespaces, as well as the JDBC escape syntax, on Postgres then when you move to another database you could drop namespace usage and everything should continue working fine.

Alternatively, if you are not planning multiple database support, using Postgres's own 'select' syntax (e.g. "SELECT \* FROM pruebas.prueba();") seems like the best idea.

**Comment by vanecanhete** [comment] 2014-08-18 15:16
Ok, thank you for the answers. I'll use the search path.

**Comment by brettwooldridge** [comment] 2014-10-23 02:59
Sounds like this issue has been resolved with an acceptable solution.

**Closed as completed by brettwooldridge** 2014-10-23 02:59 UTC
Labels: type: bug
