### ISSUE TITLE
Cannot parse Version of current docker image?

### ISSUE THREAD

**Issue by Framstag** [impossibl/pgjdbc-ng#387] opened 2019-02-09 20:19 UTC
I have setup a minimal test application in Kotlin to work against a postgres database using the official docker image from here: https://hub.docker.com/_/postgres

Testcode:
```kotlin
package com.framstag.domainbus

import mu.KotlinLogging
import java.sql.DriverManager

val logger = KotlinLogging.logger("main")

fun main(args: Array<String>) {
    val url = "jdbc:pgsql://localhost/postgres"
    val user = "postgres"
    val password = "postgres"


    logger.info("Opening connection...")
    val connection = DriverManager.getConnection(url, user, password)

    logger.info("Closing connection...")
    connection.close()

    logger.info("done.")

}
```

The PosgreSQL Instance was started using:
```
docker run --rm=true -it -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres postgres
```

Kotlin code uses your driver as dependency:
```xml
        <dependency>
            <groupId>com.impossibl.pgjdbc-ng</groupId>
            <artifactId>pgjdbc-ng</artifactId>
            <version>0.8.1</version>
        </dependency>
```

Besides a number of exceptions because I'm missing native netty support libraries I get:
```
Exception in thread "main" com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: java.lang.IllegalArgumentException: Invalid version string: 11.1 (Debian 11.1-3.pgdg90+1)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:137)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:212)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:165)
	at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:113)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.framstag.domainbus.DomainBusKt.main(DomainBus.kt:15)
Caused by: java.io.IOException: java.lang.IllegalArgumentException: Invalid version string: 11.1 (Debian 11.1-3.pgdg90+1)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.translateConnectionException(ServerConnectionFactory.java:585)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:258)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:150)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:131)
	at com.impossibl.postgres.system.BasicContext.<init>(BasicContext.java:187)
	at com.impossibl.postgres.jdbc.PGDirectConnection.<init>(PGDirectConnection.java:221)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:203)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Invalid version string: 11.1 (Debian 11.1-3.pgdg90+1)
	at com.impossibl.postgres.system.Version.parse(Version.java:52)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.startup(ServerConnectionFactory.java:516)
	at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:207)
	... 10 more
```
Seems you like to version to match against a regular expression (have seen the code), but the expression looks rather complex...is my setup wrong (looks like the version string from postgres looks OK in principle) or your regular expression? How to workaround?

**Comment by kdubb** [comment] 2019-02-09 20:23
Duplicate of #385?  Try `0.8.2-SNAPSHOT`

**Comment by Framstag** [comment] 2019-02-10 08:33
I tested with 0.8.2 (releases just a few hours ago :-)) and it seems to work now. Thanks for the fast response.

**Closed as completed** 2019-02-10 08:33 UTC
