### ISSUE TITLE
Issues with the prepared statement cache

### ISSUE THREAD

**Issue by gsmet** [impossibl/pgjdbc-ng#117] opened 2014-11-12 19:16 UTC
Hi,

I just got hit by the prepared statement cache: at least if you're using PostgreSQL 9.1, the driver forces PostgreSQL to generate a suboptimal plan by preparing the statement without any parameter values.

Some background about PostgreSQL and prepared statements:

Release note item of PostgreSQL 9.1:
~~
Protocol-level unnamed prepared statements are re-planned for each set of BIND values (Tom)
This improves performance because the exact parameter values can be used in the plan.
~~

Release note item of PostgreSQL 9.2:
~~
Allow the planner to generate custom plans for specific parameter values even when using prepared statements (Tom Lane)

In the past, a prepared statement always had a single "generic" plan that was used for all parameter values, which was frequently much inferior to the plans used for non-prepared statements containing explicit constant values. Now, the planner attempts to generate custom plans for specific parameter values. A generic plan will only be used after custom plans have repeatedly proven to provide no benefit. This change should eliminate the performance penalties formerly seen from use of prepared statements (including non-dynamic statements in PL/pgSQL).
~~

FWIW, a simple proximity query using PostGIS goes from a few 100ms with the old driver to 57 _seconds_ with pgjdbc-ng because pgjdbc-ng's cache is using a generic plan without taking into account the parameters of the query: thus, the plan is awfully suboptimal and doesn't use our geographic index.

We then tried to disable the cache and it was a long and painful journey:
- we tried to set it up with a dataSource property but we couldn't get it to work (we use HikariCP);
- we then tried with a URL parameter but it does not work due to https://github.com/impossibl/pgjdbc-ng/issues/87 (Brett, I commented your fix, it does not work property - at least with Java 7);
- we finally got the parameter transmitted to the driver after a few fixes based on what Brett did in his repo;
- then we got hit by the biggest issue: we _always_ send a statement name even if the cache is disabled and it's not a good idea as PostgreSQL then throws errors due to the fact that you try to reparse a statement using a name already used: see https://github.com/brettwooldridge/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/jdbc/PGPreparedStatement.java#L179

I'm not convinced having this cache enabled by default is a good idea but we should really provide a simple way to disable it because it can be harmful.

For the time being, I'm back to the original driver for this project.

Happy to discuss it further!
## 

Guillaume

**Comment by brettwooldridge** [comment] 2014-11-13 01:05
Prepared statements are usually considered a "big win" in terms of performance.  So, it seems like we need to figure out how to do it "right" with respect to 9.1/9.2, in a backward compatible way.  From reading that, it sounds like prepared statements should not be named, otherwise PostgreSQL will not generate unique plans based on bound variables.

At the same time, if unique plans are generated for every invocation of a prepared statement based on the unique values specified, I'm not sure how this doesn't wind up being _more_ expensive in the general case.  One of the supposed benefits of preparing statements is so that the plan generation only occurs once.

**Comment by kdubb** [comment] 2014-11-13 08:29
I'm taking another look into passing the parameters to the prepare command.  It was designed to be that way from the start but I ran into issues with expected type casting; the server does none in the binary protocol.  Currently sending the parameters breaks 9 unit tests. Some in trivial others in non-trivial ways. I fear that there is a deeper issue as well that isn't being caught by test coverage.  I will add a branch with this enabled and see how that works.

**Comment by brettwooldridge** [comment] 2014-11-13 12:35
I'm not trying to boast, truly, but I am driving a lot of traffic here from the HikariCP project, which itself is exploding in popularity.  So we might expect many more people trying and testing the pgjdbc-ng driver in the coming months.  On the good news front, I've had several reports of users happily using pgjdbc-ng in production, nascent as it is, with no issues.

**Comment by gsmet** [comment] 2014-11-13 17:21
@kdubb I don't think it's the way to go: if you cache the plan with a set of parameters, it might be wrong for another set of parameters. A nice example of this type of query: look for the restaurants in NY with a radius of 5 km then look for the restaurants in a small city with a radius of 5 km. In one case, you'll have thousands of answers, in the other one only a few. Add a couple of joins and your query plan will be completely different in both cases. And if you use the same one based on the small city parameters, your query on NY is going to be awfully slow.

Note: it's not a theorical problem, it's a typical issue a lot of people have (and we had this one on a lot of projects). Even when PostgreSQL has all the elements to choose the "best" plan, it sometimes is not sufficient.

Named prepared statements are good _if_ you are executing a set of queries for which you can expect a pretty similar result. Let's say a simple query on the primary key or a batch get/load of similar objects or even complex queries with a pretty similar distribution of your data. But they can really cause problems if it's not the case.

A lot of people used the protocolVersion=3 parameter for the old driver until 9.1 because plans were horrible even for unnamed prepared statements (with v3 the parameters were injected in the query by the driver before sending the query to the server). We started using version 4 of the protocol for complex applications with a lot of data when we started using 9.1.

My point is the following:
- if I want a named prepared statement, I can do it explicitely in my code;
- the driver automatically replacing unnamed prepared statements by cached named prepared statements is a bad thing;
- if you want to propose an option to activate a cache for prepared statement plans, it might be useful for people but it shouldn't be the default setting.

@brettwooldridge As for me, I discovered HikariCP when I started to work on pgjdbc-ng.

We use it in production for a couple of months for a couple of our applications.

It doesn't change the fact that if you have a big database with a non linear distribution of your data, you will have problem with the cache.

And it's not a rare problem: see all the discussions about the statistics on pgsql-hackers (selectivity, ndistinct, correlated statistics and so on).

**Comment by gsmet** [comment] 2014-11-13 18:41
Status as of now:
- we tried to set it up with a dataSource property but we couldn't get it to work (we use HikariCP);

-> pull request sent to HikariCP: https://github.com/brettwooldridge/HikariCP/pull/190
- we then tried with a URL parameter but it does not work due to #87 (Brett, I commented your fix, it does not work property - at least with Java 7)

-> pull request sent: https://github.com/impossibl/pgjdbc-ng/pull/119
- then we got hit by the biggest issue: we always send a statement name even if the cache is disabled and it's not a good idea as PostgreSQL then throws errors due to the fact that you try to reparse a statement using a name already used: see https://github.com/brettwooldridge/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/jdbc/PGPreparedStatement.java#L179 

-> waiting for a decision on the cache: if we disable it by default, I think the no cache path shouldn't pay for the overhead of the cache and the fix won't be the same.

## 

Guillaume

**Comment by gsmet** [comment] 2014-11-14 07:23
Looks like the problem can also happen with recent versions of PostgreSQL if after a couple of executions a generic plan is bogusly considered better than the custom plans.

See http://markmail.org/thread/w6pqsexlzbsmlpmj .

So I really think we should get rid of the cache in the default case. It can really lead to bogus behaviors.

**Comment by kdubb** [comment] 2014-11-16 19:58
@gsmet The cache key takes into account the parameter types.  I am definitely not an expert, or even a beginner, on the topic of query planning but you are saying that `WHERE dist=5 AND city='ny'` and  `WHERE dist=5 AND city='smalltown'` can create two different query plans.  This I would consider interesting to the almost magical level.  If that is indeed the case then we could hash the parameters as well when creating a cache key. Either using the Object.hash or hashing the serialized form as they are being sent for the prepare.

Although, it seems obvious we should support disabling the cache, I do tend to agree with @brettwooldridge that generally the cache is going to be a win.  Along those lines I'm thinking a "Do not cache" pool would be an excellent option as well.  For example, adding a method like:

```
PGDriver.disableCache(PreparedStatement stmt)
```

This would allow you to leave the cache enabled but for a problematic query specifically disable any queries like it.  I'm thinking passing a PreparedStatment in is better that just raw SQL to ensure whatever the driver does to the SQL would be easily supported.  What do you think of this idea?

**Comment by brettwooldridge** [comment] 2014-11-16 22:59
Similar to @kdubb, the question I have is what happens in the case:

``` sql
<complex query> WHERE dist=? AND city-=?
```

... or a query with tens of replacement parameters that is executed tens or hundreds of times with differing values?  It seems by far the exception than the rule that it is more efficient to compile a unique plan for each set of values.

**Comment by brettwooldridge** [comment] 2014-11-17 00:37
After reading the markmail thread, this comment from Tom Lane (God among men):

```
| David Johnston <davi...@gmail.com> writes:
| While "planner hints" comes to mind...on the SQL side can we extend the
| "PREPARE" command with two additional keywords?â
|
| PREPARE
|  name [ ( data_type [, ...] ) ] [
|  [NO] GENERIC
|  ] â
| AS statement

Don't really see the point.  The OP's problem is that the prepare is
being driven by a client-side library, which would have even less clue
than the backend as to whether a generic plan is more appropriate than
a custom plan.

The right thing here IMO is to improve the heuristics on the backend
side.  I'm sure we can do better, it's just going to take some thought.
```

Here we are the "client-side library", and we indeed "have even less clue
than the backend as to whether a generic plan is more appropriate than
a custom plan."

Other than, as @kdubb suggesting, allowing a user to explicitly exclude a query from the cache I am not sure there is much we can do.  Except, possibly excluding non-PreparedStatements from the cache entirely.  So that `Connection.createStatement()` and the resulting `statement.execute()` prepare plans with the values as specified rather than in a generic form (we may already do this, I haven't looked).

**Comment by gsmet** [comment] 2014-11-17 20:12
@kdubb PostgreSQL keeps statistics to be able to choose the best plan for the query.

For instance, if you have an index on your conditions and the statistics tell that you are returning very few rows, the planner will use an index scan on the index. If the statistics tell that you are returning a lot of rows, it will use a seq scan.

@brettwooldridge personnally, I use unnamed statements when I don't want to reuse the plan: it's effectively the rule in our applications: you can't be sure a generic plan will be good enough (on small databases, you probably don't see it but you really see the problem on big databases with a non standard distribution of data). That's why I think we shouldn't cache the unnamed prepared statements by default. If I want to cache the plan, I use a named prepared statement.

**Comment by geraldodev** [comment] 2014-12-04 23:46
@brettwooldridge 

with prepared statements 'where field like ?' takes the worst scenario and does not use index for 'JOHN%'

**Comment by brettwooldridge** [comment] 2014-12-05 02:26
@gsmet The aforementioned bugs should be fixed (pull request?).  There should certainly be an option to disable the cache, in which case pgjdbc-ng should probably use unnamed prepared statements.  I also like @kdubb's idea that even when the cache is enabled, a mechanism to exclude statements (force unnamed) would cover most cases where suboptimal plans would be reused due to naming.

@geraldodev I would consider this a bug with respect to PostgreSQL.  In this case, PostgreSQL knows the type of 'field', and knows there is a 'like' operator against that column in the query, not choosing an index-scan on the appropriate index in this case sounds like a bug to me.

**Comment by geraldodev** [comment] 2014-12-05 09:42
@brettwooldridge That was true for <= 9.1. 

From 9.2 that's not true anymore:
http://blog.endpoint.com/2014/04/custom-plans-prepared-statements-in.html

This fact makes me think that one using 9.1 might not want prepared statements at all with like statements

**Comment by brettwooldridge** [comment] 2014-12-05 10:47
@geraldodev I agree.  I'm glad to see PostgreSQL has improved in this respect.

**Comment by Redeeman** [comment] 2015-01-04 17:05
@gsmet 

> > "personnally, I use unnamed statements when I don't want to reuse the plan: it's effectively the rule in our applications: you can't be sure a generic plan will be good enough (on small databases, you probably don't see it but you really see the problem on big databases with a non standard distribution of data). That's why I think we shouldn't cache the unnamed prepared statements by default. If I want to cache the plan, I use a named prepared statement."

Sorry but what do you mean here? are you issuing PREPARE "yourself" for the queries you feel should be stored serverside, and then EXECUTEing them "youself" too? And what do you mean with "unnamed prepared statements" ? I do not know the postgres protocol, but im guessing this is internal to how the protocol works, but what is your suggestion then? to disable turning preparedstatements into named prepared statements unless you mark the prepared statement as should end up named?

**Comment by kdubb** [comment] 2015-01-05 15:36
@Redeeman This is very much related to the Postgres backend protocol itself.  The driver issues a protocol level prepare (basically equivalent to a PREPARE statement) whenever you use a PreparedStatement.  Unnamed prepared statements are an internal mechanism that is used to execute a statement with parameters without "keeping it around" like a general prepare does.  There is only ever 1 unnamed prepared statement, each time the old one is overwritten when making a request.

**Comment by slorion** [comment] 2015-01-05 17:44
Sorry to hijack this thread, but since you are discussing the prepared statement cache, would you mind considering making it possible to disable it altogether via the connection string parameter `?prepareThreshold=0` ? This would allow pgjdbc-ng to work with PgBouncer in transaction pooling mode as explained here: http://engineering.clever-cloud.com/java/2013/05/27/pgjdbc-now-pgbouncer-compliant.html.

**Comment by kdubb** [comment] 2019-01-07 08:57
This is a quite old issue and I believe it's no longer relevant in the current driver. There are two caches with regard to prepared statements at this point, a description cache (described statement with no parameter types) which is used to work out what parameter types are required, then a prepared statement cache that includes SQL text and parameter types; which directly solves the originating problem.

Also, it seems PostgreSQL has done a bit of work in this area.  Any other performance related issues can be conveyed via a new ticket.

**Closed as completed by kdubb** 2019-01-07 08:57 UTC
Labels: type: question
