### ISSUE TITLE
Unhandled message: C @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler java.lang.IllegalStateException: Unhandled message: C

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#458] opened 2019-11-06 12:24 UTC
I'm now getting this:

```
2019.11.06 13:21:31 [pool-2-thread-9] [null] [F397101258136ZGZMAO] ERROR no.officenet.origo.core.integration.QueueActor.$anonfun.applyOrElse:88:30 - Error in QUEUE_CONSUMER: Unhandled message: C @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler
java.lang.IllegalStateException: Unhandled message: C @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler
        at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.dispatch(MessageDispatchHandler.java:214)
        at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.channelRead(MessageDispatchHandler.java:149)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:315)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:429)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at com.impossibl.shadow.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at com.impossibl.shadow.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at com.impossibl.shadow.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at com.impossibl.shadow.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:830)
```

How shall I proceed with debugging this?

**Comment by kdubb** [comment] 2019-11-06 14:33
Closing as a duplicate of #457 Please attach this information on that issue.

**Closed as completed by kdubb** 2019-11-06 14:33 UTC

**Comment by andreak** [comment] 2019-11-07 17:06
Actually, this issue comes from the fact that EclipseLink sends a "pingSQL", defined in `PostgreSQLPlatform.pingSQL`, after the `TooLongFrameException` has occured.
This are the last log-lines on the server (PG-log)
```
2019-11-07 14:36:52.075 CET [16700-52] andreak@rev LOG:  execute cached-65948c5b: SELECT DISTINCT t1.entity_id, t1.part_type, t1.filename, t1.part_index, t1.mimetype, t1.raw_content_filename, t1.size, t1.uid, t1.version, t1.message_id, t1.parent_id, t1.charset, t1.string_content, t1.multipart_type, t0.entity_id, t0.header_index, t0.header_name, t0.version, t0.part_id FROM origo_email_part t1 LEFT OUTER JOIN origo_email_part_header t0 ON (t0.part_id = t1.entity_id) WHERE (t1.parent_id = $1) ORDER BY t1.part_index ASC
2019-11-07 14:36:52.075 CET [16700-53] andreak@rev DETAIL:  parameters: $1 = '1'
2019-11-07 14:36:52.632 CET [16700-54] andreak@rev LOG:  execute lo.close: select lo_close($1)
2019-11-07 14:36:52.632 CET [16700-55] andreak@rev DETAIL:  parameters: $1 = '1'
2019-11-07 14:36:52.632 CET [16700-56] andreak@rev LOG:  execute TR: ROLLBACK
2019-11-07 14:36:52.632 CET [16700-57] andreak@rev ERROR:  prepared statement "cached-3fcfe755" already exists
2019-11-07 14:36:52.632 CET [16700-58] andreak@rev STATEMENT:  SELECT 1
```
The last `SELECT 1` is from when EclipseLink calls `DatabasePlatform.wasFailureCommunicationBased` to check of the connection is still valid after the `TooLongFrameException: Adjusted frame length exceeds 20971520: 29028470 - discarded` error has occured, masking the error. So I don't really consider this issue closed nor fixed as it should be clear what the error is, not just `Unhandled message` which isn't very helpfull.

**Comment by kdubb** [comment] 2019-11-07 19:22
Keep this database handy, if you can. I agree that a more "graceful" failure here is wanted.

TooLongFrameException generating a much better error message (easy to do) and resetting the message dispatch state so as not to be "confused" (much harder to do) would be really helpful here.

**Comment by andreak** [comment] 2019-11-07 20:03
It's no problem keeping this database around.
