### ISSUE TITLE
WARNING: cleaning up leaked connection

### ISSUE THREAD

**Issue by eklipse2k8** [impossibl/pgjdbc-ng#129] opened 2015-01-14 22:41 UTC
I am getting a leaked connection warning overtime Hikari tries to clean up idle connections.

```
Jan 14, 2015 9:34:29 PM com.impossibl.postgres.jdbc.ThreadedHousekeeper$HousekeeperReference cleanup
WARNING: cleaning up leaked connection
  at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:398)
  at com.zaxxer.hikari.pool.HikariPool.lambda$addBagItem$2(HikariPool.java:309)
  at com.zaxxer.hikari.pool.HikariPool$$Lambda$7/1618043679.run(Unknown Source)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:744)
```

**Comment by frkline** [comment] 2015-01-21 19:35
Had the same issue. Disabling the pgjdbc-ng housekeeper did the trick for me as per
https://groups.google.com/forum/#!msg/hikari-cp/zqgCOjzyd_k/hF9s5spz9GMJ

**Comment by kdubb** [comment] 2015-01-27 03:56
@brettwooldridge Are you under the belief that this is due to a bug in our Housekeeper?

**Comment by brettwooldridge** [comment] 2015-01-27 04:37
@kdubb I'm not sure this is a bug in the pgjdbc-ng driver.  Obviously a connection pool tends to keep connections open for quite some time, so it could just be that the concept of "leak detection" at the driver level is inherently incompatible with use within a pool.  If that is the case, disabling the housekeeper seems like an appropriate solution.

One thing that does trouble me a bit is that the log seems to be emitted at the point where a new Connection is created (`addConnection()` above).  I'm not sure why a warning would be emitted at that point vs. some point in the future.  Looking at the `ThreadedHousekeeper`, I have to admit being a bit lost as to what is going on with threads, phantom references, and what not.

**Comment by kdubb** [comment] 2015-01-27 04:45
Ok. I think I can clear up the discrepancy here.  The log message should be amended to read "Cleaning up leaked connection (stack trace of allocation follows)". The stack trace is the point of allocation not the point of "leaking".

Also, the housekeeper runs purely off of Java references.  It's warning you that all of an object's references have fell completely out of scope and is now being cleaned up because somebody let it go without doing so (which is against the JDBC spec).  This is implemented in place of the dreaded "finalize".

So... provided pgjdbc-ng is working correctly... a connection allocated in the addConnection method has lost all of it's references without having been closed.

**Comment by brettwooldridge** [comment] 2015-01-27 04:58
If that is the case, it would seem to point to an issue with the pool.  I will add some additional debug log messages in HikariCP, but it would also be extremely useful if pgjdbc-ng can include the Connection.toString() of the leaked Connection in it's log message.  In that way, hopefully matches can be made between the HikariCP logs and the pgjdbc-ng logs.

If it is _not_ an issue on the HikariCP side, which it certainly may be, it would indicate some path whereby a Connection is closed, aborted, or terminated in a way that does not clear the reference tracking in the ThreadedHousekeeper.

UPDATE: in short, let's leave this bug open until we get to the bottom of it.

**Comment by brettwooldridge** [comment] 2015-01-27 06:00
@kdubb looking that the ThreadedHousekeeper, I see that the [remove()](https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/jdbc/ThreadedHousekeeper.java#L249) method removes the tracked connection from the `cleanupReferences` hash set, but the phantom reference is still going to be [dequeued](https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/jdbc/ThreadedHousekeeper.java#L183) from the `ReferenceQueue` and no check is performed that the `HousekeeperReference` still exists in the set.  So it looks like the [`ref.cleanup()`](https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/jdbc/ThreadedHousekeeper.java#L119) is always going to fire and log a warning.  Am I missing something?

**Comment by kdubb** [comment] 2015-01-27 06:34
@brettwooldridge When working properly, for `close` to be called there must be a hard reference to the connection and inside the call to `close` the `HousekeeperReference` is removed from `cleanupReferences`.  Once the `HousekeeperReference` loses all of its references, the JVM can no longer enqueue it; notice that nowhere in the code itself does any `HousekeeperReference` get added to the queue as that is done by the JVM. PhantomReference and its workings are a real mind bender so it's always fun to try and understand or explain.

**Comment by brettwooldridge** [comment] 2015-01-27 15:05
@eklipse2k8 I have been doing some testing with HikariCP 2.3.1 + pgjdbc-ng (0.5-SNAPSHOT) and I have been unable to reproduce this exception.  Could you try with the latest versions of both libraries and let me know if you still see this issue?

**Comment by eklipse2k8** [comment] 2015-01-27 18:49
@brettwooldridge sure, let me give it a try. The exception doesn't happen consistently, so it might be hard to reproduce in a short window.

**Comment by tomdearman** [comment] 2015-05-22 08:19
Did anyone get to the bottom of this issue.  We are seeing the above connection leak message and prepared statement leak message.  We are using hibernate and it is pretty clear that hibernate does call the statement close method so I can't see how the statement is leaked. We are seeing this pretty regularly so could run a version with extra debug is it would help resolve the issue.

**Comment by jesperpedersen** [comment] 2015-05-26 12:47
@tomdearman Are you seeing this with 0.6 ? And what other frameworks are you using w/ version info

**Comment by tomdearman** [comment] 2015-05-26 13:21
We are running pgjdbc-ng 0.5 (there dont seem to have been any commits for 0.6 other than version), hikari 2.3.2 and:
        <version.spring>4.1.5.RELEASE</version.spring>
        <version.spring.boot>1.2.3.RELEASE</version.spring.boot>
        <version.hibernate>4.3.8.Final</version.hibernate>
        <version.infinispan>6.0.2.Final</version.infinispan>
and a lot of other frameworks that are not transactional.

**Comment by jesperpedersen** [comment] 2015-05-26 13:22
Yeah, ignore my 0.6 comment - I was looking at my tree :)

**Comment by kdubb** [comment] 2016-07-14 09:13
I believe I've finally caught the cause of these seemingly random warnings; they were actually valid.  Details in the PR that fixes them #273

**Comment by kdubb** [comment] 2017-01-06 19:48
Reopening since we are encountering this, essentially, all the time.  Just starting our server, running some tests (opens database connection(s)), then letting the server sit idle causes this issue.  It seems to be when the pool (in this case, HikariCP) releases the connection after an idle timeout. 

@brettwooldridge Any thoughts on what we can do to help track this down?  I'm building a PR of changes to help.  I have a few housekeeper related logs added and have started logging the connection string (which you referenced above).  Any other thoughts would be great.

**Comment by kdubb** [comment] 2017-01-09 02:05
Adding collected log here for safekeeping.

<details>
<summary>Clean up logging (expand it)</summary>

```
2017-01-08 17:27:03.800  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 888889933)
2017-01-08 17:27:07.480  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1653098001)
2017-01-08 17:27:09.240  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1746791573)
2017-01-08 17:27:09.632  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1652336490)
2017-01-08 17:27:10.345  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1933289491)
2017-01-08 17:27:11.139  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 82418983)
2017-01-08 17:27:11.435  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1244708453)
2017-01-08 17:27:13.526  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1136333752)
2017-01-08 17:27:15.334  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1482093018)
2017-01-08 17:27:16.921  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1206213784)
2017-01-08 17:27:17.422  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1454922213)
2017-01-08 17:27:17.898  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1304386256)
2017-01-08 17:27:21.476  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1488943362)
2017-01-08 17:27:21.564  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 265471588)
2017-01-08 17:27:22.515  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 872295698)
2017-01-08 17:27:25.577  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 109435958)
2017-01-08 17:27:27.022  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1594876737)
2017-01-08 17:27:28.019  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 2140511786)
2017-01-08 17:27:28.768  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1222794742)
2017-01-08 17:27:29.305  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 164033447)
2017-01-08 17:27:31.649  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1969368739)
2017-01-08 17:27:33.630  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 755846464)
2017-01-08 17:27:37.278  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1940494994)
2017-01-08 17:27:39.704  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1610135722)
2017-01-08 17:27:39.775  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1922490408)
2017-01-08 17:27:39.855  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 390160832)
2017-01-08 17:27:41.567  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 950594985)
2017-01-08 17:27:41.605  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 26836923)
2017-01-08 17:27:41.795  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 726598582)
2017-01-08 17:27:44.457  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1289489912)
2017-01-08 17:56:36.525  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 328878673)
2017-01-08 17:56:37.872  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 144613553)
2017-01-08 17:56:39.308  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 2078605793)
2017-01-08 17:57:01.360  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1792863775)
2017-01-08 17:57:02.442  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 923850209)
2017-01-08 17:57:02.927  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 164680908)
2017-01-08 17:57:05.110  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1990620565)
2017-01-08 17:57:06.070  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1266187229)
2017-01-08 17:57:08.056  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 998461255)
2017-01-08 17:57:08.205  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1595476343)
2017-01-08 17:57:09.193  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1198717772)
2017-01-08 17:57:10.354  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1770256948)
2017-01-08 17:57:11.182  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1339673892)
2017-01-08 17:57:11.911  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 431331418)
2017-01-08 17:57:12.473  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1993922858)
2017-01-08 17:57:12.529  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1889353598)
2017-01-08 17:57:13.197  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1858288867)
2017-01-08 17:57:13.398  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1895071690)
2017-01-08 17:57:13.458  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 2085023395)
2017-01-08 17:57:15.563  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1732420382)
2017-01-08 17:57:16.164  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1435572331)
2017-01-08 17:57:24.557  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1376363265)
2017-01-08 17:57:25.575  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 163636922)
2017-01-08 17:57:26.135  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 775844508)
2017-01-08 17:57:29.775  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1551265893)
2017-01-08 17:57:30.862  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 714334490)
2017-01-08 17:57:30.972  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 2086912105)
2017-01-08 17:57:34.824  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1776587337)
2017-01-08 17:57:37.761  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 739516069)
2017-01-08 17:57:42.571  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 51714656)
2017-01-08 18:21:28.253  WARN 24305 --- [DBC Housekeeper] c.i.p.j.ThreadedHousekeeper              : Cleaning up leaked connection[ jdbc:pgsql://localhost/retxt_cloud ] (id: 1993922858)
Allocation occurred @
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
  at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

2017-01-08 18:21:28.253  WARN 24305 --- [DBC Housekeeper] c.i.p.j.ThreadedHousekeeper              : Cleaning up leaked connection[ jdbc:pgsql://localhost/retxt_cloud ] (id: 739516069)
Allocation occurred @
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
  at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

2017-01-08 18:21:28.253  WARN 24305 --- [DBC Housekeeper] c.i.p.j.ThreadedHousekeeper              : Cleaning up leaked connection[ jdbc:pgsql://localhost/retxt_cloud ] (id: 775844508)
Allocation occurred @
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
  at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

2017-01-08 18:21:28.253  WARN 24305 --- [DBC Housekeeper] c.i.p.j.ThreadedHousekeeper              : Cleaning up leaked connection[ jdbc:pgsql://localhost/retxt_cloud ] (id: 1776587337)
Allocation occurred @
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
  at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
  at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

2017-01-08 18:26:17.812  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 2081893593)
2017-01-08 18:26:21.184  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1660799511)
2017-01-08 18:26:26.325  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 112267843)
2017-01-08 18:26:42.886  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1277789680)
2017-01-08 18:26:45.676  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 526277354)
2017-01-08 18:26:46.053  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 714382230)
2017-01-08 18:26:47.606  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 57547631)
2017-01-08 18:26:47.853  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 481132903)
2017-01-08 18:26:49.118  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 74751733)
2017-01-08 18:26:50.126  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1993143447)
2017-01-08 18:26:51.588  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 965149570)
2017-01-08 18:26:51.805  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 691075753)
2017-01-08 18:26:52.696  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 198702074)
2017-01-08 18:26:53.453  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1462578243)
2017-01-08 18:26:55.224  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 480654634)
2017-01-08 18:26:56.625  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1488966065)
2017-01-08 18:27:00.554  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 416338030)
2017-01-08 18:27:03.187  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1887368753)
2017-01-08 18:27:03.716  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1136361203)
2017-01-08 18:27:05.919  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 796319806)
2017-01-08 18:27:06.770  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 409638910)
2017-01-08 18:27:11.444  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 188863578)
2017-01-08 18:27:12.199  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1015477773)
2017-01-08 18:27:12.320  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 730407695)
2017-01-08 18:27:13.613  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1660465743)
2017-01-08 18:27:15.669  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 702733433)
2017-01-08 18:27:35.583  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1052007686)
2017-01-08 18:27:36.353  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1311054361)
2017-01-08 18:27:45.357  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 2057423344)
2017-01-08 18:27:45.605  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 2046565257)
2017-01-08 18:56:05.065  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1548195398)
2017-01-08 18:56:10.528  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1401397871)
2017-01-08 18:56:11.908  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 537635490)
2017-01-08 18:56:26.626  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 786769688)
2017-01-08 18:56:31.754  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1216572956)
2017-01-08 18:56:32.115  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1561024078)
2017-01-08 18:56:32.916  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1301783650)
2017-01-08 18:56:38.572  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1928443091)
2017-01-08 18:56:44.018  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1742021021)
2017-01-08 18:56:45.682  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1774104807)
2017-01-08 18:56:47.091  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1975929710)
2017-01-08 18:56:50.835  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1638756018)
2017-01-08 18:56:54.519  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1038864519)
2017-01-08 18:56:59.410  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 719913699)
2017-01-08 18:56:59.997  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1211766030)
2017-01-08 18:57:00.481  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 553859432)
2017-01-08 18:57:01.218  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1994676102)
2017-01-08 18:57:02.722  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1452493498)
2017-01-08 18:57:04.672  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1658811170)
2017-01-08 18:57:11.884  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1546115883)
2017-01-08 18:57:12.595  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 724251550)
2017-01-08 18:57:13.472  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1566573346)
2017-01-08 18:57:13.847  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1181019864)
2017-01-08 18:57:13.887  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1864157873)
2017-01-08 18:57:14.794  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 270754140)
2017-01-08 18:57:16.271  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 92702785)
2017-01-08 18:57:17.121  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1947779758)
2017-01-08 18:57:20.379  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1256877332)
2017-01-08 18:57:20.591  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 1374593287)
2017-01-08 18:57:41.243  WARN 24305 --- [nnection closer] c.i.p.s.BasicContext                     : Cleaning up houskeeper reference (id: 563881246)
```

</details>

**Comment by brettwooldridge** [comment] 2017-01-09 03:46
@kdubb HikariCP has much more detailed debug logging now compared to when this bug was opened, including logs indicating when a connection was created and added to the pool, as well as a log when a connection is closed.  Enabling debug logging for com.zaxxer.hikari should shed some new light on what is happening, especially if as you say this is easily reproducible in your environment just running a few simple tests.

**Comment by kdubb** [comment] 2017-01-09 04:32
@brettwooldridge Good to know.  Right now, after perusing the log posted above, I'm thinking it's a false positive from the `ThreadedHousekeeper`.  The log shows that all of the connections that were reported as leaked were previously explicitly closed.

 I'm _hoping_ its due to the lack of calling `PhantomReference.clear`. According to the docs:
> Unlike soft and weak references, phantom references are not automatically cleared by the garbage collector as they are enqueued. An object that is reachable via phantom references will remain so until all such references are cleared or themselves become unreachable.

Since these docs aren't all that clear, my current hope is that everything gets cleaned up properly but since `PhantomReference.clear` isn't being called then _sometimes_ the `PhantomReference` stays enqueued and _somehow, magically_ it's getting removed twice.

**Comment by kdubb** [comment] 2017-01-10 05:56
Commit 159cefe86ea047169ece022f38bf518032cf8dae clears the `PhantomReference`s after usage.  I'm not exactly sure why this fixes the false positives but 30 hours and counting without one; fingers crossed.

Also, this may fix the seemingly random Housekeeper warnings that popup while running tests; previously I thought these were due to actual leaks but maybe not.

**Comment by kdubb** [comment] 2017-01-12 01:02
After days of testing with multiple servers under different conditions we have no recorded false positives; it appears it may be fixed.  Closing until evidence proves otherwise.

**Closed as completed by kdubb** 2017-01-12 01:02 UTC

**Comment by ghost** [comment] 2019-05-25 17:47
in spring application:
> com.impossibl.postgres.jdbc.ThreadedHousekeeper$HousekeeperReference: Cleaning up leaked statement
Allocation occurred @
  at ru.anp.AnpApplication.pgConnect(AnpApplication.java:98)
  at ru.anp.AnpApplication.run(AnpApplication.java:59)
  at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
  at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
  at ru.bryu.anp.AnpApplication.main(AnpApplication.java:45)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
  at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
  at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

**Comment by vp-mazekine** [comment] 2021-03-15 10:06
Hey guys, sorry for a noob question here, but I face this issue, too.
How does the app know that the connection has closed? 
Any advice on how to monitor it or process correctly?
