### ISSUE TITLE
Question: the road to 0.4

### ISSUE THREAD

**Issue by gsmet** [impossibl/pgjdbc-ng#85] opened 2014-05-07 09:26 UTC
Hi,

Could we discuss the plan to release 0.4? A couple of important bugs have been fixed and it would be nice to release something.

My 2 cents: I would like to have this fixed before the release:
- commit https://github.com/gmokki/pgjdbc-ng/commit/c5d2c32aa1a9baee2e1ffc7c21c9d2e59398c3b9 and https://github.com/gmokki/pgjdbc-ng/commit/56f4729287dcbdec6513eb648067243695324d7f from the PR https://github.com/impossibl/pgjdbc-ng/pull/73
  -> I can merge them/update them and create a new PR with only these commits updated to work with current develop branch.
- commit: https://github.com/impossibl/pgjdbc-ng/pull/84
- I was wondering if we should update the Guava classes. I have something for all the classes except the *Streams classes. Did you clean unused methods in these classes to reduce the dependency to other Guava classes or did the Guava guys added a lot of stuff?

See if we can fix:
https://github.com/impossibl/pgjdbc-ng/issues/65
https://github.com/impossibl/pgjdbc-ng/issues/81

Thanks for your feedback.

**Comment by kdubb** [comment] 2014-05-07 13:21
- #73 Go for it, don't see a problem
- #84 Don't see a problem
- #65 Is currently not reproducible but should be an easy fix once a test case is committed
- #81 We need to compare with mainline driver to see if the problem exists there as well because the test cases were adapted from there

Updating Guava classes is doable bit tricky.  Also, so little of them is used that I am not sure it's worth it unless we found a bug.   The shade plug-in did a real shitty job of slimming down the Guava classes; most likely do to the severe interdependencies of the code.  For this reason the classes were copied in by hand and stripped of all but the used methods, plus those that had no dependencies.  I'd say we ignore this for now.

**Comment by gsmet** [comment] 2014-07-03 15:51
Sorry for not having followed up. Very busy at work then vacation.

Here is the current status:
- I've merged the changes Mikko made in #73 in #91 . I think you or Brett can commit #91 without any issue.
- #84 : it would be nice if either you or Brett could commit it.
- I haven't updated the Guava classes. I totally agree with you on this point.

Once these 2 PR are merged, I think it could be a good idea to release a 0.4 version as we have people reporting already fixed issues.

Edit: it might be a good idea to take a look at https://github.com/impossibl/pgjdbc-ng/issues/89 too. But I'm not sure it's worth postponing a release if it's a complicated issue.

FWIW, we develop our new applications using 0.4-SNAPSHOT for a while without any issues and it would be great to have an official release.

Thanks!

**Comment by kdubb** [comment] 2014-07-03 16:48
I agree with all you've said here.

I will commit #91 & #84 ASAP.  I will look into #89, although I believe it is a bit of a complicated issue and may be better off being put in the next release.

Once these are settled I'll move to 0.4 release.  It is long overdue & 0.4-SNAPSHOT had been working very well for quite a while.  I believe I'll have this done before Monday.

**Comment by gsmet** [comment] 2014-07-03 17:29
Nice. Thanks!

**Comment by gsmet** [comment] 2014-07-10 06:58
Hi Kevin!

Any news about the release? We're waiting for an official release before putting a few apps into production. Thanks!

**Comment by kdubb** [comment] 2014-08-17 04:36
0.4 has finally been released... You'll notice I didn't specify which Monday :grin:

**Closed as completed by kdubb** 2014-08-17 04:36 UTC
Labels: type: question

**Comment by gsmet** [comment] 2014-08-18 06:56
Thanks Kevin!
